version: '3.8'

networks:
  triple:
    external: true
    name: triple
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - triple

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - triple
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_internal
      - ELASTICSEARCH_PASSWORD=kibanaPw
    networks:
      - triple
    depends_on:
      - elasticsearch

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: triple-application
    ports:
      - "8080:8080"
    environment:
      - elasticsearch.host=elasticsearch
      - elasticsearch.port=9200
    depends_on:
      - elasticsearch
    networks:
      - triple
